"""added details in company table

Revision ID: 59cdd77363f3
Revises: 40cd33cd7ed5
Create Date: 2025-03-26 08:37:19.775431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59cdd77363f3'
down_revision: Union[str, None] = '40cd33cd7ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('year_of_assignment', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('start_audit_period', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('end_audit_period', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'end_audit_period')
    op.drop_column('companies', 'start_audit_period')
    op.drop_column('companies', 'year_of_assignment')
    # ### end Alembic commands ###
