"""add title and desc to docs_request table

Revision ID: f582181a65f0
Revises: 59cdd77363f3
Create Date: 2025-04-16 09:24:02.420799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f582181a65f0'
down_revision: Union[str, None] = '59cdd77363f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_requests', sa.Column('request_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document_requests', sa.Column('request_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_requests', 'request_desc')
    op.drop_column('document_requests', 'request_title')
    # ### end Alembic commands ###
